[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
nft_contract = "65USePYd9nzjHHBFrSp9oxWjZKVJacE2Hx28aFpPkVpn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"